baseURL = "https://kaleidochain.io/en"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = "Kaleido"
theme = "syna"

[params]
  name = "Kaleido"


[[menu.main]]
  url = ""
  name = "Home"
  weight = 1

[[menu.main]]
  url = "https://kallet.kaleidochain.io"
  name = "Wallet"
  weight = 10

[[menu.main]]
  url = "https://kalscan.io"
  name = "Explorer"
  weight = 20

[[menu.main]]
  url = "https://docs.kaleidochain.io/"
  name = "Docs"
  weight = 30

[[menu.main]]
  url = "https://kaleidochain.io/zh"
  name = "ZH"
  weight = 90

[[menu.footer]]
  url = "docs/whitepaper_en.pdf"
  name = "Whitepaper"
  weight = 5

[[menu.footer]]
  url = "https://docs.kaleidochain.io"
  name = "Documentation"
  weight = 7

[[menu.footer]]
  url = "https://kallet.kaleidochain.io"
  name = "Wallet"
  weight = 10

[[menu.footer]]
  url = "https://kalscan.io"
  name = "Explorer"
  weight = 20

[[menu.footer]]
  url = "https://weibo.com/unicointop"
  name = "Weibo"
  weight = 25

[[menu.footer]]
  url = "https://digifinex.vip"
  name = "DigiFinex"
  weight = 30

[[menu.footer]]
  url = "https://www.feixiaohao.com/currencies/kaleidotoken/"
  name = "Feixiaohao"
  weight = 40

#[[menu.copyright_footer]]
#  url = "/about/"
#  name = "关于我们"
#  weight = 10
#
#[[menu.copyright_footer]]
#  url = "/faq/"
#  name = "常见问题"
#  weight = 20
#
