baseURL = "https://kaleidochain.io/vi"
languageCode = "vi-VN"
defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false
title = "Kaleido"
theme = "syna"

[params]
  name = "Kaleido"


[[menu.main]]
  url = ""
  name = "Trang nhà"
  weight = 1

[[menu.main]]
  url = "https://kaleidochain.io/en/wallet"
  name = "Ví tiền"
  weight = 10

[[menu.main]]
  url = "https://kalscan.io"
  name = "Trình duyệt blockchain"
  weight = 20

[[menu.main]]
  url = "https://docs.kaleidochain.io/"
  name = "Tài liệu dành cho nhà phát triển"
  weight = 30

[[menu.footer]]
  url = "kaleido_whitepaper_en.pdf"
  name = "Sách trắng"
  weight = 5

[[menu.footer]]
  url = "https://docs.kaleidochain.io"
  name = "Tài liệu dành cho nhà phát triển"
  weight = 7

[[menu.footer]]
  url = "https://t.me/joinchat/ORkdNxAhTMKgb1lFprYRKw"
  name = "Nhóm điện báo"
  weight = 8

[[menu.footer]]
  url = "https://kaleidochain.io/en/wallet"
  name = "Ví tiền"
  weight = 10

[[menu.footer]]
  url = "https://kalscan.io"
  name = "Trình duyệt blockchain"
  weight = 20

[[menu.footer]]
  url = "https://weibo.com/unicointop"
  name = "Weibo chính thức"
  weight = 25

[[menu.footer]]
  url = "https://digifinex.com"
  name = "Sàn giao dịch DigiFinex"
  weight = 30

[[menu.footer]]
  url = "https://www.feixiaohao.com/currencies/kaleidotoken/"
  name = "Nền tảng trích dẫn"
  weight = 40

#[[menu.copyright_footer]]
#  url = "/about/"
#  name = "关于我们"
#  weight = 10
#
#[[menu.copyright_footer]]
#  url = "/faq/"
#  name = "常见问题"
#  weight = 20
#
